### ISSUE TITLE
FileNotFoundError: can't find hsds-node executable

### ISSUE THREAD

**Issue by Will-Gorman** [HDFGroup/hsds#262] opened 2023-09-25 16:21 UTC
I am seeing the same issue as #211, but I think its for the more basic issue of potentially not having a potential location in PATH. But, I am not sure what I need to add on my Windows machine to PATH.

When I try to start the HSDS server with runall.bat in my hsds python environment I get:

DEBUG:root:looking for hsds-servicenode in PATH env var folders
INFO:root:using cmd_dir: C:\Users\wgorman\Anaconda3\envs\hsds\Scripts
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\wgorman\Anaconda3\envs\hsds\Scripts\hsds.exe\__main__.py", line 7, in <module>
  File "C:\Users\wgorman\Anaconda3\envs\hsds\Lib\site-packages\hsds\app.py", line 356, in main
    app.run()
  File "C:\Users\wgorman\Anaconda3\envs\hsds\Lib\site-packages\hsds\hsds_app.py", line 268, in run
    raise FileNotFoundError("can't find hsds-node executable")
FileNotFoundError: can't find hsds-node executable

And when I run hsds-node, I get an error: "no node_type argument found"

What location do I need to add to PATH? I will say that I have an hsds-servicenode.exe file in the C:\Users\wgorman\Anaconda3\envs\hsds\Scripts PATH. 

Also echo %PATH% does show the C:\Users\wgorman\Anaconda3\envs\hsds\Scripts folder

**Comment by jreadey** [comment] 2023-10-03 05:03
Seems the problem is that the build system creates "hsds-node.exe" on Windows and the hsds driver is looking for a file with the name "hsds-node".  
I have what should be a fix checked into master now.  I've also pushed a new version of the HSDS package (v 0.8.4) to PyPI, so you can get the new package with just: `pip install hsds --upgrade`.
Let me know if this resolves the issue.

**Comment by jreadey** [comment] 2023-10-10 16:27
This should be resolved in the new release - please re-open if you are still seeing it.

**Closed by jreadey** 2023-10-10 16:27 UTC
Labels: bug
